[package]
name = "io_at"
version = "0.1.0"
authors = ["edef"]
edition = "2018"

[dependencies]
libc = { version = "*", optional = true }
void = { version = "*", default-features = false }

[features]
default = ["std"]
std = ["libc"]
