[package]
name = "git"
version = "0.1.0"
authors = ["edef"]
edition = "2018"

[dependencies]
void = { version = "*", default-features = false }
gulp = { path = "../gulp" }
sha1dc = { path = "../sha1dc" }
