[workspace]
members = [
    "io_at",
    "gulp",
    "git",
    "git_delta",
    "git_delta/fuzz",
    "git_packfile",
    "git_packfile/fuzz",
    "verify"
]

[patch.crates-io]
void = { path = "void" }
