[package]
name = "git_packfile"
version = "0.1.0"
authors = ["edef"]

[dependencies]
void = "*"
safe_shl = { path = "../safe_shl" }
byteorder = "*"
gulp = { path = "../gulp" }
git = { path = "../git" }
