[package]
name = "git_delta"
version = "0.1.0"
edition = "2018"

[dependencies]
gulp = { path = "../gulp" }
safe_shl = "*"
failure = { version = "*", default-features = false, features = ["derive"] }

[features]
std = ["gulp/std", "failure/std"]
nightly = []
