[package]
name = "systest"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
miniz-sys = { path = '../miniz-sys' }
libc = "0.2"

[build-dependencies]
ctest = "0.2.0"
