[package]
name = "gulp"
version = "0.1.0"
authors = ["edef"]
edition = "2018"

[dependencies]
void = { version = "*", default-features = false }
failure = { version = "*", default-features = false, features = ["derive"] }
safe_shl = "*"
