[package]
name = "git_pack"
version = "0.1.0"
authors = ["edef"]
edition = "2018"

[dependencies]
safe_shl = "*"
byteorder = "*"
failure = { version = "*", default-features = false, features = ["derive"] }
gulp = { path = "../gulp" }
git = { path = "../git" }
