language: rust

matrix:
  include:
    - rust: stable
    - os: osx
    - rust: beta
    - rust: nightly

    - rust: stable
      script: cargo run --manifest-path systest/Cargo.toml
      name: "systest"

    - rust: nightly
      install: rustup target add wasm32-unknown-unknown
      script: cargo build --target wasm32-unknown-unknown
      name: "wasm"

    - rust: stable
      env: RUST_BACKEND=1
      script:
        - cargo test --features rust_backend
        - cargo test --features rust_backend --no-default-features

    - name: "master doc to gh-pages"
      rust: nightly
      script:
        - cargo doc --no-deps --all-features
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        skip_cleanup: true
        on:
          branch: master

  allow_failures:
    - env: RUST_BACKEND=1

script:
  - cargo build
  - rustdoc --test README.md -L target/debug/deps --extern flate2=target/debug/libflate2.rlib
  - cargo test
  - cargo test --features zlib
  - cargo test --features tokio
  - cargo test --features 'tokio zlib'
  - cargo test --features zlib --no-default-features

branches:
  only:
    - master

notifications:
  email:
    on_success: never
